import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#0A0F0A',
    color: '#E8F5E9',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    borderTopWidth: 1,
    borderTopColor: '#1E2D1E',
    paddingTop: 8,
    fontSize: 8,
    color: '#4A6741',
    textAlign: 'center',
  },
  // Cover page
  coverLogo: {
    fontSize: 32,
    color: '#2ECC71',
    fontFamily: 'Helvetica-Bold',
    marginBottom: 4,
  },
  coverTagline: {
    fontSize: 11,
    color: '#81C784',
    marginBottom: 48,
  },
  coverTitle: {
    fontSize: 28,
    fontFamily: 'Helvetica-Bold',
    color: '#E8F5E9',
    marginBottom: 8,
  },
  coverSubtitle: {
    fontSize: 13,
    color: '#81C784',
    marginBottom: 40,
  },
  gradeBox: {
    backgroundColor: '#111A11',
    borderWidth: 1,
    borderColor: '#1E2D1E',
    borderRadius: 12,
    padding: 24,
    marginBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 24,
  },
  gradeLetter: {
    fontSize: 64,
    fontFamily: 'Helvetica-Bold',
    marginRight: 24,
  },
  gradeLabel: {
    fontSize: 14,
    color: '#81C784',
    marginTop: 4,
  },
  statRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#111A11',
    borderWidth: 1,
    borderColor: '#1E2D1E',
    borderRadius: 8,
    padding: 16,
  },
  statLabel: {
    fontSize: 9,
    color: '#4A6741',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  statValue: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: '#E8F5E9',
  },
  statUnit: {
    fontSize: 10,
    color: '#81C784',
    marginTop: 2,
  },
  // Section headers
  sectionTitle: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: '#2ECC71',
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#1E2D1E',
  },
  // Table
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#162016',
    padding: '8 12',
    borderRadius: 4,
    marginBottom: 4,
  },
  tableRow: {
    flexDirection: 'row',
    padding: '8 12',
    borderBottomWidth: 1,
    borderBottomColor: '#1E2D1E',
  },
  tableCell: {
    fontSize: 10,
    color: '#E8F5E9',
  },
  tableHeaderCell: {
    fontSize: 9,
    color: '#4A6741',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontFamily: 'Helvetica-Bold',
  },
  // Insight
  headlineCard: {
    backgroundColor: '#1A7A42',
    borderRadius: 10,
    padding: 20,
    marginBottom: 20,
  },
  headlineText: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: '#E8F5E9',
  },
  actionCard: {
    backgroundColor: '#111A11',
    borderWidth: 1,
    borderColor: '#1E2D1E',
    borderRadius: 8,
    padding: 14,
    marginBottom: 10,
  },
  actionText: {
    fontSize: 11,
    color: '#E8F5E9',
    marginBottom: 6,
  },
  actionMeta: {
    fontSize: 9,
    color: '#81C784',
  },
  noInsight: {
    fontSize: 12,
    color: '#4A6741',
    textAlign: 'center',
    marginTop: 40,
  },
});

interface CategoryData {
  category: string;
  label: string;
  icon: string;
  co2_kg: number;
  amount_usd: number;
  pct: number;
  color: string;
}

interface GradeInfo {
  grade: string;
  colour: string;
  label: string;
}

interface InsightAction {
  action: string;
  estimated_reduction_pct: number;
  effort: string;
  local_context: string;
}

interface InsightData {
  headline?: string;
  top_category_insight?: {
    category: string;
    finding: string;
    three_actions: InsightAction[];
  };
  benchmark_note?: string;
}

interface ReportProps {
  categoryData: CategoryData[];
  totalCO2: number;
  totalSpend: number;
  grade: GradeInfo;
  startDate: string;
  endDate: string;
  generatedAt: string;
  companyName: string;
  insightData: InsightData | null;
}

export function EcoTraceReport({
  categoryData,
  totalCO2,
  totalSpend,
  grade,
  startDate,
  endDate,
  generatedAt,
  companyName,
  insightData,
}: ReportProps) {
  const footer = (
    <Text style={styles.footer}>
      Generated by EcoTrace · Ignite Hack 2.0 · Carbon data sourced from EPA GHG Protocol
    </Text>
  );

  return (
    <Document>
      {/* Page 1 — Cover */}
      <Page size="A4" style={styles.page}>
        <View>
          <Text style={styles.coverLogo}>🌿 EcoTrace</Text>
          <Text style={styles.coverTagline}>Decarbonizing Commerce, One Transaction at a Time.</Text>

          <Text style={styles.coverTitle}>Carbon Impact Report</Text>
          <Text style={styles.coverSubtitle}>{companyName}</Text>
          <Text style={{ fontSize: 11, color: '#4A6741', marginBottom: 32 }}>
            Reporting Period: {startDate} to {endDate}
          </Text>

          {/* Grade */}
          <View style={styles.gradeBox}>
            <Text style={[styles.gradeLetter, { color: grade.colour }]}>{grade.grade}</Text>
            <View>
              <Text style={{ fontSize: 18, fontFamily: 'Helvetica-Bold', color: '#E8F5E9' }}>
                Carbon Grade
              </Text>
              <Text style={styles.gradeLabel}>{grade.label}</Text>
            </View>
          </View>

          {/* Stats */}
          <View style={styles.statRow}>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>Total CO₂ Footprint</Text>
              <Text style={styles.statValue}>
                {totalCO2.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </Text>
              <Text style={styles.statUnit}>kg CO₂</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>Total Spend Tracked</Text>
              <Text style={styles.statValue}>
                ${totalSpend.toLocaleString('en-US', { maximumFractionDigits: 0 })}
              </Text>
              <Text style={styles.statUnit}>USD</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statLabel}>Generated</Text>
              <Text style={{ fontSize: 11, color: '#E8F5E9', marginTop: 4 }}>{generatedAt}</Text>
            </View>
          </View>
        </View>
        {footer}
      </Page>

      {/* Page 2 — Breakdown */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Emissions Breakdown by Category</Text>

        {/* Table header */}
        <View style={styles.tableHeader}>
          <Text style={[styles.tableHeaderCell, { flex: 2 }]}>Category</Text>
          <Text style={[styles.tableHeaderCell, { flex: 1, textAlign: 'right' }]}>Spend (USD)</Text>
          <Text style={[styles.tableHeaderCell, { flex: 1, textAlign: 'right' }]}>CO₂ (kg)</Text>
          <Text style={[styles.tableHeaderCell, { flex: 1, textAlign: 'right' }]}>% of Total</Text>
        </View>

        {categoryData.map((cat) => (
          <View key={cat.category} style={styles.tableRow}>
            <Text style={[styles.tableCell, { flex: 2 }]}>{cat.label}</Text>
            <Text style={[styles.tableCell, { flex: 1, textAlign: 'right' }]}>
              ${cat.amount_usd.toLocaleString('en-US', { maximumFractionDigits: 0 })}
            </Text>
            <Text style={[styles.tableCell, { flex: 1, textAlign: 'right', color: '#2ECC71' }]}>
              {cat.co2_kg.toFixed(2)}
            </Text>
            <Text style={[styles.tableCell, { flex: 1, textAlign: 'right', color: '#81C784' }]}>
              {cat.pct}%
            </Text>
          </View>
        ))}

        {/* Total row */}
        <View style={[styles.tableRow, { backgroundColor: '#162016', borderRadius: 4, marginTop: 8 }]}>
          <Text style={[styles.tableHeaderCell, { flex: 2, fontSize: 10 }]}>TOTAL</Text>
          <Text style={[styles.tableHeaderCell, { flex: 1, textAlign: 'right', fontSize: 10 }]}>
            ${totalSpend.toLocaleString('en-US', { maximumFractionDigits: 0 })}
          </Text>
          <Text style={[styles.tableHeaderCell, { flex: 1, textAlign: 'right', fontSize: 10, color: '#2ECC71' }]}>
            {totalCO2.toFixed(2)}
          </Text>
          <Text style={[styles.tableHeaderCell, { flex: 1, textAlign: 'right', fontSize: 10 }]}>100%</Text>
        </View>

        {footer}
      </Page>

      {/* Page 3 — AI Insights */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>AI Sustainability Insights</Text>

        {insightData ? (
          <View>
            {insightData.headline && (
              <View style={styles.headlineCard}>
                <Text style={styles.headlineText}>{insightData.headline}</Text>
              </View>
            )}

            {insightData.top_category_insight && (
              <View>
                <Text style={{ fontSize: 13, fontFamily: 'Helvetica-Bold', color: '#81C784', marginBottom: 8 }}>
                  Top Emission Source: {insightData.top_category_insight.category}
                </Text>
                <Text style={{ fontSize: 11, color: '#E8F5E9', marginBottom: 16 }}>
                  {insightData.top_category_insight.finding}
                </Text>

                <Text style={{ fontSize: 11, color: '#4A6741', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 }}>
                  Recommended Actions
                </Text>
                {insightData.top_category_insight.three_actions?.map((action, i) => (
                  <View key={i} style={styles.actionCard}>
                    <Text style={styles.actionText}>{i + 1}. {action.action}</Text>
                    <Text style={styles.actionMeta}>
                      Effort: {action.effort} · Est. Reduction: {action.estimated_reduction_pct}%
                    </Text>
                    {action.local_context && (
                      <Text style={[styles.actionMeta, { color: '#4A6741', marginTop: 4 }]}>
                        💡 {action.local_context}
                      </Text>
                    )}
                  </View>
                ))}
              </View>
            )}

            {insightData.benchmark_note && (
              <Text style={{ fontSize: 10, color: '#4A6741', marginTop: 16, fontStyle: 'italic' }}>
                {insightData.benchmark_note}
              </Text>
            )}
          </View>
        ) : (
          <Text style={styles.noInsight}>
            Generate AI Insights first to include recommendations in this report.
          </Text>
        )}

        {footer}
      </Page>
    </Document>
  );
}
